### ISSUE TITLE
ux-checkbox

### ISSUE THREAD

**Issue by Vheissu** [aurelia/ux#22] opened 2016-11-24 06:51 UTC
Implement the ux-checkbox component for Material and iOS design.

- [x] Material Design
- [ ] iOS Design

**Comment by Vheissu** [comment] 2016-11-24 06:51
I'll take this one @EisenbergEffect if you can assign it to me.

**Comment by ZHollingshead** [comment] 2017-04-05 13:04
@Vheissu are you still working on this? I am looking to snag a couple quick components to knock out.

**Comment by dspublic** [comment] 2017-05-02 17:02
@ZHollingshead I tried your ux-checkbox component with custom string value. The "delete this.checked" isn't clears the property. Would not the "this.checked=null" be better?

**Comment by ZHollingshead** [comment] 2017-05-02 19:18
@dspublic yes, it appears you are correct. I am looking into this, thanks for the catch!

**Comment by ZHollingshead** [comment] 2017-05-02 19:35
@dspublic I just pushed a fix to master.

**Comment by dspublic** [comment] 2017-05-03 09:22
@ZHollingshead Thank you for quick fix and response. Let me take a feature suggestion, what I implemented in my checkbox control. 
There's a valueOn (value-on default=true) and valueOff (value-off default=false) and value (checked in your code) controll property.
If value==valueOn then value=valueOff
elseIf value==valueOff or value==null then value=valueOn
else value=null (third state)
In this case we have a value for state on and off, and a null for third one.
I think, your solution is close enough to this logic. What do you mean?

**Comment by ZHollingshead** [comment] 2017-05-03 11:49
So if I understand correctly you would like to add additional values to be able to set a value during the unchecked state, is this correct? If so I would probably just add the unchecked state, and let value continue to represent the checked state.

``` html
<ux-checkbox value="foo" unchecked-value="bar"></ux-checkbox>
```

**Comment by dspublic** [comment] 2017-05-03 12:31
@ZHollingshead Yes, that's correct. It's exactly what I want to suggest. 
Thanks for your selfless work in this project. :-)

**Comment by ZHollingshead** [comment] 2017-09-01 04:25
Issue moved to [aurelia/ux-components #12](https://github.com/aurelia/ux-components/issues/12) via [**ZenHub**](https://www.zenhub.com/)

**Comment by veikkoeeva** [comment] 2018-02-21 17:06
@ZHollingshead A question, is https://aux-demo.firebaseapp.com/checkbox missing a design component only? It appears there are other components too that look like implemented, but open here.

**Comment by ZHollingshead** [comment] 2018-02-21 17:51
@veikkoeeva what do you mean by design component?

A list of all the component packages can be seen here:
Source Code: https://github.com/aurelia/ux/tree/master/packages
Feature List: https://github.com/aurelia/ux/wiki/Feature-List

**Comment by veikkoeeva** [comment] 2018-02-21 17:57
@ZHollingshead I mean if I read correctly this -- and some other tickets -- that the pending work is related to iOS and this isn't something that's lingering in open state. It appears the case is such that this indeed is pending on some further work, though the component is useable already.

**Comment by ZHollingshead** [comment] 2018-02-21 18:01
The component is useable as is. The design feature will not be a separate component, that will be part of the `@aurelia-ux/core` package. Work on this functionality is not yet complete.

**Closed** 2018-11-07 16:05 UTC
Labels: feature, new component
